<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../bib/ArquivoTexto.class.php';

/**
 * Test class for ArquivoTexto.
 * Generated by PHPUnit on 2010-04-20 at 15:38:43.
 */
class ArquivoTextoTest extends PHPUnit_Framework_TestCase {
    /**
     * @var ArquivoTexto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testLer().
     */
    public function testLer() {
        $arquivo = dirname(__FILE__).'/../../log/naoexiste.log';
        $this->object = new ArquivoTexto($arquivo);
        $this->assertFalse($this->object->ler());
        $arquivo = dirname(__FILE__).'/../../log/ERRO20100324.log';
        $this->object = new ArquivoTexto($arquivo);
        $this->assertTrue($this->object->ler());
    }

    /**
     * @todo Implement testEscrever().
     */
    public function testEscrever() {
        $arquivo = dirname(__FILE__).'/../../log/testeEscrita.log';
        $this->object = new ArquivoTexto($arquivo);
        $this->assertTrue($this->object->criar());
        $this->assertTrue($this->object->escrever("ALAN\n"));
        $this->assertTrue($this->object->escrever("GUSTAVO\n"));
        $resultado = $this->object->leConteudo();
        $this->assertEquals("ALAN\n", $resultado[0]);
        $this->assertEquals("GUSTAVO\n", $resultado[1]);
        $this->assertTrue($this->object->deletar());

    }

    /**
     *
"Wed, 24 Mar 10 10:15:32 -0300	localhost	ALAN	Testando o Log		850a5b3abcffa8ca1f0cec0570706ba6"
"Wed, 24 Mar 10 10:16:19 -0300	localhost	ALAN	Testando o Log		6f99473dd87381f4403e1cf9563dfdec"
"Wed, 24 Mar 10 10:36:31 -0300	localhost	ALAN	Testando o Log		1213799aa9beb8a73e45fee96649107e"
"Wed, 24 Mar 10 10:37:02 -0300	localhost	ALAN	Testando o Log		82b56d5d12d14fc7f78ff36fd508425b"
"Wed, 24 Mar 10 20:44:04 -0300	localhost	ALAN	Testando o Log		89155cdc81d6f80e3ed2ec3da38731fa"
     */
    public function testLeConteudo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
