<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../bib/Arquivo.class.php';

/**
 * Test class for Arquivo.
 * Generated by PHPUnit on 2010-04-20 at 15:38:25.
 */
class ArquivoTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Arquivo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testArquivoExiste().
     */
    public function testArquivoExiste() {
        $this->object = new Arquivo("ArquivoTest.php");
        $this->assertTrue($this->object->arquivoExiste());
        $this->object = new Arquivo("ArquivoInexistente.php");
        $this->assertFalse($this->object->arquivoExiste());
        $arquivo = dirname(__FILE__).'/../../log/ERRO20100324.log';
        $this->object = new Arquivo($arquivo);
        $this->assertTrue($this->object->arquivoExiste());
        $arquivo = dirname(__FILE__).'/../../log/naoexiste.log';
        $this->object = new Arquivo($arquivo);
        $this->assertFalse($this->object->arquivoExiste());
    }
    /**
     * Teste para a criação de arquivos
     */
    public function testCriar() {
        $arquivo = dirname(__FILE__).'/../../log/teste.tst';
        $this->object = new Arquivo($arquivo);
        $this->assertTrue($this->object->criar());
    }
    /**
     * Teste para a criação de arquivos
     */
    public function testDeletar() {
        $arquivo = dirname(__FILE__).'/../../log/teste.tst';
        $this->object = new Arquivo($arquivo);
        $this->assertTrue($this->object->deletar());
    }

}
?>
