<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../bib/Conexao.class.php';

/**
 * Test class for Conexao.
 * Generated by PHPUnit on 2010-04-20 at 15:38:54.
 */
class ConexaoTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Conexao
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Conexao;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetConexao().
     */
    public function testGetConexao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPegConexao().
     */
    public function testPegConexao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIniTransacao().
     */
    public function testIniTransacao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFimTransacao().
     */
    public function testFimTransacao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
