<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../bib/Conf.class.php';

/**
 * Test class for Conf.
 * Generated by PHPUnit on 2010-04-20 at 15:39:12.
 */
class ConfTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Conf
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Conf;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testAltCHAVE().
     */
    public function testAltCHAVE() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPegCHAVE().
     */
    public function testPegCHAVE() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPegCnxPadrao().
     */
    public function testPegCnxPadrao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExibeTodosErros().
     */
    public function testExibeTodosErros() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testOcultaTodosErros().
     */
    public function testOcultaTodosErros() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
