<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__).'/../../bib/Depurar.class.php';

/**
 * Test class for Depurar.
 * Generated by PHPUnit on 2010-04-22 at 14:17:52.
 */
class DepurarTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Depurar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testReg().
     * Estou tendo problemas para utilizar os testes com Métodos e Classes Estáticas
     */
    public function testReg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
?>
