<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../bib/Log.class.php';

/**
 * Test class for Log.
 * Generated by PHPUnit on 2010-04-20 at 15:38:08.
 */
class LogTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Log;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testReg().
     */
    public function testReg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testValidaLog().
     */
    public function testValidaLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
